---
- name: Install docker
  hosts: jenkins_server
  become: true
  tasks:
    - name: Install docker
      dnf:
        name: docker
        update_cache: true
        state: latest
    - name: Start docker daemon
      service:
        name: docker
        state: started

- name: Add ec2-user to docker group
  hosts: jenkins_server
  become: true
  tasks:
    - name: Add ec2-user to docker group
      user:
        name:  ec2-user
        groups: docker
        append: true

- name: Run jenkins as container
  hosts: jenkins_server
  tasks:
    - name: Start container
      docker_container:
        name: jenkins
        image: jenkins/jenkins:latest-jdk21
        state: started
        restart_policy: on-failure
        ports:
          - "80:8080"
          - "50000:50000"
        volumes:
          - jenkins_home:/var/jenkins_home


    
      