name: Simple todo ci/cd pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:


jobs:
  build:
    name: Build and test image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Calculate short SHA
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ vars.DOCKERHUB_USERNAME }}/simple_todo:$calculatedSha"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
          
      - name: Build image
        uses: docker/build-push-action@v7
        with:
          context: .
          tags: ${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Setup jdk
        uses: actions/setup-java@v6.0.1
        with:
          java-version: 25
  
      - name: Test
        run: |
          ./mvnw -Dapp.image=${{ env.IMAGE_TAG }} test

